# Generated by Django 4.2 on 2025-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('PROG', 'En Progreso'), ('DONE', 'Completada')], default='PEND', max_length=4),
        ),
    ]
